# Generated by Django 5.0.7 on 2024-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDetails',
        ),
        migrations.DeleteModel(
            name='IssueDetails',
        ),
        migrations.AddField(
            model_name='issue',
            name='date_solved',
            field=models.DateTimeField(null=True),
        ),
    ]
