# Generated by Django 5.0.7 on 2024-07-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_commentdetails_delete_issuedetails_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                CREATE VIEW comment_details AS
                SELECT
                    c.id AS comment_id,
                    i.id AS issue_connected,
                    i.title AS issue_title,
                    c.content AS comment_content,
                    c.date_posted AS comment_date,
                    e.first_name AS author_first_name,
                    e.last_name AS author_last_name,
                    e.email AS author_email
                FROM
                    app_comments c
                JOIN
                    app_employee e ON c.author_id = e.id,
                    app_issue i ON c.issue_commented_id = i.id
            '''
        ),
        migrations.RunSQL(
            '''
                CREATE VIEW issue_details AS
                SELECT
                    i.id AS issue_id,
                    i.title AS issue_title,
                    i.content AS issue_content,
                    i.date_posted AS issue_date,
                    i.is_solved,
                    i.labels,
                    e.first_name AS author_first_name,
                    e.last_name AS author_last_name,
                    e.email AS author_email,
                    e.Degisnation AS author_degisnation
                FROM
                    app_issue i
                JOIN
                    app_employee e ON i.author_id = e.id
            '''
        ),
        migrations.RunSQL(
            '''
                CREATE VIEW daily_summary AS
                SELECT
                    date,
                    SUM(issues_created) AS issues_created,
                    SUM(issues_solved) AS issues_solved,
                    SUM(comments_created) AS comments_created
                FROM (
                    SELECT
                        date(date_posted) AS date,
                        COUNT(*) AS issues_created,
                        0 AS issues_solved,
                        0 AS comments_created
                    FROM app_issue
                    GROUP BY date(date_posted)

                    UNION ALL

                    SELECT
                        date(date_solved) AS date,
                        0 AS issues_created,
                        COUNT(*) AS issues_solved,
                        0 AS comments_created
                    FROM app_issue
                    WHERE date_solved IS NOT NULL
                    GROUP BY date(date_solved)

                    UNION ALL

                    SELECT
                        date(date_posted) AS date,
                        0 AS issues_created,
                        0 AS issues_solved,
                        COUNT(*) AS comments_created
                    FROM app_comments
                    GROUP BY date(date_posted)
                ) AS combined
                GROUP BY date
                ORDER BY date;

            '''
        )
    ]
