# Generated by Django 5.0.7 on 2024-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetails',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_connected', models.IntegerField()),
                ('issue_title', models.CharField(max_length=50)),
                ('comment_content', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'comment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('issues_solved', models.IntegerField()),
                ('issues_created', models.IntegerField()),
                ('comments_created', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssueDetails',
            fields=[
                ('issue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=50)),
                ('issue_content', models.TextField()),
                ('issue_date', models.DateTimeField()),
                ('is_solved', models.BooleanField()),
                ('labels', models.TextField()),
                ('author_first_name', models.CharField(max_length=150)),
                ('author_last_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_degisnation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'issue_details',
                'managed': False,
            },
        ),
    ]
